### ISSUE TITLE
bug: unhead build error on vite-ssg

### ISSUE THREAD

**Issue by liyasthomas** [unjs/unhead#230]
### Environment

"@unhead/vue": "^1.5.2",
"vite-ssg": "^0.23.1".

Node: v20.4.0

### Reproduction

[stackblitz.com/edit/github-ngu39o?file=package.json&view=editor&startScript=build](https://stackblitz.com/edit/github-ngu39o?file=package.json&view=editor&startScript=build)

### Describe the bug

Vite SSG build fails with the following error:
```
Error: [vite-ssg] Error on page: /
TypeError: head._popSideEffectQueue is not a function
```

### Additional context

Similar issue: https://github.com/antfu/vite-ssg/issues/368.

### Logs

```sh
5:48:42 PM: ✓ built in 1.36s
5:48:42 PM: [vite-ssg] Rendering Pages... (26)
5:48:43 PM: file:///opt/build/repo/node_modules/.pnpm/vite-ssg@0.23.1_@unhead+vue@1.7.3_vite@4.4.9_vue-router@4.2.4_vue@3.3.4/node_modules/vite-ssg/dist/node.mjs:1066
5:48:43 PM:         throw new Error(`${gray([vite-ssg])} ${red(`Error on page: ${cyan(route)}`)}
              ^

Error: [vite-ssg] Error on page: /products
TypeError: head._popSideEffectQueue is not a function
    at renderDOMHead (file:///opt/build/repo/node_modules/.pnpm/@unhead+dom@1.1.32/node_modules/@unhead/dom/dist/index.mjs:52:33)
    at async file:///opt/build/repo/node_modules/.pnpm/vite-ssg@0.23.1_@unhead+vue@1.7.3_vite@4.4.9_vue-router@4.2.4_vue@3.3.4/node_modules/vite-ssg/dist/node.mjs:1052:11
    at async file:///opt/build/repo/node_modules/.pnpm/vite-ssg@0.23.1_@unhead+vue@1.7.3_vite@4.4.9_vue-router@4.2.4_vue@3.3.4/node_modules/vite-ssg/dist/node.mjs:635:36
    at file:///opt/build/repo/node_modules/.pnpm/vite-ssg@0.23.1_@unhead+vue@1.7.3_vite@4.4.9_vue-router@4.2.4_vue@3.3.4/node_modules/vite-ssg/dist/node.mjs:1066:15
    at async file:///opt/build/repo/node_modules/.pnpm/vite-ssg@0.23.1_@unhead+vue@1.7.3_vite@4.4.9_vue-router@4.2.4_vue@3.3.4/node_modules/vite-ssg/dist/node.mjs:635:36
```
```

**Comment by harlan-zw** [comment]
You can probably resolve by using `resolutions` in your package.json for `unhead`, otherwise I sent a PR for vite-ssg.

**Comment by harlan-zw** [comment]
Please try the latest version of `vite-ssg`
