### ISSUE TITLE
Vite, using useHead and useSeoMeta in same file doesn't work

### ISSUE THREAD

**Issue by RickRosendaal** [unjs/unhead#407]
### Environment

`node -v`: `v18.18.2`
`yarn -v`: `1.22.19`
`"@vitejs/plugin-vue"`: `"5.1.4"`
`"vite"`: `"5.4.9"`
`"vue"`: `"3.3.4"`
`"@unhead/vue"`: `"1.11.9"`

### Reproduction

index.vue:
```
<template>
  <div />
</template>

<script lang="ts" setup>
import { useHead, useSeoMeta } from "@unhead/vue";

useHead({});
useSeoMeta({});
</script>
```

### Describe the bug

When using useHead and useSeoMeta in the same file, a Vite "pre-transform error" occurs:
`Pre-transform error: Failed to parse source for import analysis because the content contains invalid JS syntax.`

### Additional context

When for example moving the useSeoMeta to another file (composable), and calling that composable, the error no longer occurs.
The error also does not occur when removing either the `useHead` call or the `useSeoMeta` call.

The "converted page" (when vite's pre-transform has succeeded), will have replaced `useSeoMeta` with an `useHead` call.
e.g.
```
useSeoMeta({
  title: "Hello",
  ogDescription: () => {
    return "World";
  },
});
```
Will be transformed into:
```
useHead({
  title: "Hello",
  meta: [
    { property: 'og:description', content: () => {
        return "World";
      } },
  ]
});
```

So possibly the issue is related to the conversion where it mixes them up..?

### Logs

```sh
12:01:39 PM [vite] Pre-transform error: Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.
12:01:39 PM [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.
Plugin: vite:import-analysis
  File: /home/projects/unhead/src/pages/index.vue:13:5
  12 |      return __returned__;
  13 |    }
  14 |  });
     |  ^
  15 |  import { openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue";
  16 |  function _sfc_render(_ctx, _cache, $props, $setup, $data, $options) {
      at TransformPluginContext._formatError (file:///home/projects/unhead/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:49244:41)
      at TransformPluginContext.error (file:///home/projects/unhead/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:49239:16)
      at TransformPluginContext.transform (file:///home/projects/unhead/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:63982:14)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PluginContainer.transform (file:///home/projects/unhead/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:49085:18)
      at async loadAndTransform (file:///home/projects/unhead/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:51918:27)
      at async viteTransformMiddleware (file:///home/projects/unhead/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:61870:24)
      ```
```

**Comment by harlan-zw** [comment]
Hi, thanks for reporting this. It should be fixed in v1.11.10.
